services:
  postgres:
    image: postgres:16
    container_name: studentsdb
    environment:
      POSTGRES_DB: studentsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - students_data:/var/lib/postgresql/data

volumes:
  students_data: